[package]
name = "weather-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.3"
deunicode = "1.6.0"
indoc = "2.0.5"
weather-lib = { path = "../weather-lib" }
reqwest = { version = "0.11.22", default-features = false, features = [
    "rustls-tls-native-roots",
    "json",
] }
tokio = { version = "1.34.0", default-features = false, features = [
    "macros",
    "rt-multi-thread",
    "fs",
] }
scraper = "0.19.0"
clap = { version = "4.5.6", features = ["derive", "env"] }
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
