on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: deploy to fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: superfly/flyctl-actions/setup-flyctl@v1.4
      - run: |
          nix build .#container
          docker load < result
      - run: flyctl deploy --local-only --image "weather-server:latest"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
