on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    name: deploy to fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: superfly/flyctl-actions/setup-flyctl@v1.4
      - run: |
          nix build .#container
